/* Copyright (c) 2012-2024 ImFusion GmbH, Munich, Germany. All rights reserved. */
#pragma once

#include <ImFusion/AnatomyPlugin/KeysImpl.h>

#include <unordered_map>

/// Custom compile-time strings for different parts of human anatomy. AnatomyKeys
/// translates between names generated by TotalSegmentator and the names defined below
/// See also the Anatomy plugin copmonent guide in the SDK documentation for further technical details.
namespace TotalSegmentator::Keys
{

	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Spine)
	// Skeletal system
	ADD_KEY_CHAIN(Spine, Vertebra)
	ADD_KEY_CHAIN(Spine, Vertebra, S1)
	ADD_KEY_CHAIN(Spine, Vertebra, L5)
	ADD_KEY_CHAIN(Spine, Vertebra, L4)
	ADD_KEY_CHAIN(Spine, Vertebra, L3)
	ADD_KEY_CHAIN(Spine, Vertebra, L2)
	ADD_KEY_CHAIN(Spine, Vertebra, L1)
	ADD_KEY_CHAIN(Spine, Vertebra, T12)
	ADD_KEY_CHAIN(Spine, Vertebra, T11)
	ADD_KEY_CHAIN(Spine, Vertebra, T10)
	ADD_KEY_CHAIN(Spine, Vertebra, T9)
	ADD_KEY_CHAIN(Spine, Vertebra, T8)
	ADD_KEY_CHAIN(Spine, Vertebra, T7)
	ADD_KEY_CHAIN(Spine, Sacrum)
	ADD_KEY_CHAIN(Spine, SpinalCord)

	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, RibLeft)
	ADD_KEY_CHAIN(RibLeft, R4)
	ADD_KEY_CHAIN(RibLeft, R5)
	ADD_KEY_CHAIN(RibLeft, R6)
	ADD_KEY_CHAIN(RibLeft, R7)
	ADD_KEY_CHAIN(RibLeft, R8)
	ADD_KEY_CHAIN(RibLeft, R9)
	ADD_KEY_CHAIN(RibLeft, R10)
	ADD_KEY_CHAIN(RibLeft, R11)
	ADD_KEY_CHAIN(RibLeft, R12)

	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, RibRight)
	ADD_KEY_CHAIN(RibRight, R3)
	ADD_KEY_CHAIN(RibRight, R4)
	ADD_KEY_CHAIN(RibRight, R5)
	ADD_KEY_CHAIN(RibRight, R6)
	ADD_KEY_CHAIN(RibRight, R7)
	ADD_KEY_CHAIN(RibRight, R8)
	ADD_KEY_CHAIN(RibRight, R9)
	ADD_KEY_CHAIN(RibRight, R10)
	ADD_KEY_CHAIN(RibRight, R11)
	ADD_KEY_CHAIN(RibRight, R12)

	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, ScapulaLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, ScapulaRight)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, FemurLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, FemurRight)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, HipLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, HipRight)

	// Digestive system
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Liver)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Gallbladder)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Stomach)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Esophagus)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, SmallBowel)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Duodenum)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Colon)

	// Urinary system
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, LeftKidney)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, RightKidney)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, UrinaryBladder)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Prostate)

	// Lymphatic system
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Spleen)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Pancreas)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, AdrenalGland)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, AdrenalGlandLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, AdrenalGlandRight)

	// Cardiovascular system
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Heart)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Aorta)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, PulmonaryVein)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, AtrialAppendageLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, SuperiorVenaCava)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, InferiorVenaCava)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, PortalVeinAndSplenicVein)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, IliacArteryLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, IliacArteryRight)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, IliacVenaLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, IliacVenaRight)

	// Respiratory system
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Lung)
	ADD_KEY_CHAIN(Lung, UpperLobeLeft)
	ADD_KEY_CHAIN(Lung, LowerLobeLeft)
	ADD_KEY_CHAIN(Lung, UpperLobeRight)
	ADD_KEY_CHAIN(Lung, MiddleLobeRight)
	ADD_KEY_CHAIN(Lung, LowerLobeRight)

	// Muscles
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, GluteusMaximusLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, GluteusMaximusRight)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, GluteusMediusLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, GluteusMediusRight)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, GluteusMinimusLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, GluteusMinimusRight)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, AutochthonLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, AutochthonRight)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, IliopsoasLeft)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, IliopsoasRight)

	// Rib cage - cartilages
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, Sternum)
	ADD_KEY_CHAIN_WITH_STRING_PREFIX(TotalSegmentator, CostalCartilages)


	/// Wrapper class for the keys defined above
	/// Its single static method converts a segmented volume name
	/// from string value generated by TotalSegmentator into a custom
	/// string defined with the ADD_KEY_CHAIN_WITH_STRING_PREFIX
	/// ADD_KEY_CHAIN macros
	class AnatomyKeys
	{
	public:
		/// Translate the key from nomenclature produced by TotalSegmentator into
		/// format defined above in this file
		static std::string translateKey(const std::string& keyTotalSegmentator) noexcept;

	private:
		static const std::unordered_map<std::string, std::string> m_demoToImFusionNameMap;
	};


}    /// namespace TotalSegmentator::Keys
